name: Chatify
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.0
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  shared_preferences: ^2.0.11
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.3
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  firebase_messaging: ^11.2.3
  photo_view: ^0.13.0
  http:
  font_awesome_flutter:
  bubble:
  giphy_picker: ^2.0.0
  popup_menu: ^1.0.5
  curved_navigation_bar: ^1.0.1
  permission_handler: ^8.3.0
  flutter_ringtone_player: ^3.1.1
  focused_menu: ^1.0.1
  splash_screen_view: ^3.0.0
  agora_rtc_engine: ^4.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_new.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif
    
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
